sentry-dsn = "https://glet_78c3bf45d009794a4d9b0c990a1f1ed5@gitlab.com/api/v4/error_tracking/collector/29762666"

[api]
  debug-jsonrpc = false
  enable-debug-methods = true
  enable-subscribe-tx = false
  listen-address = "http://0.0.0.0:26660"
  prometheus-server = "http://18.119.26.7:9090"
  tx-max-wait-time = "10s"

[network]
  bvn-names = ["BVN0", "BVN1", "BVN2"]
  id = "SEED"
  type = "directory"

  [network.addresses]
    BVN0 = ["http://0.bvn0.testnet.accumulatenetwork.io:33000", "http://1.bvn0.testnet.accumulatenetwork.io:33000", "http://2.bvn0.testnet.accumulatenetwork.io:33000"]
    BVN1 = ["http://0.bvn1.testnet.accumulatenetwork.io:33000", "http://1.bvn1.testnet.accumulatenetwork.io:33000", "http://2.bvn1.testnet.accumulatenetwork.io:33000"]
    BVN2 = ["http://0.bvn2.testnet.accumulatenetwork.io:33000", "http://1.bvn2.testnet.accumulatenetwork.io:33000", "http://2.bvn2.testnet.accumulatenetwork.io:33000"]
    Directory = ["http://0.bvn0.testnet.accumulatenetwork.io:34000", "http://1.bvn0.testnet.accumulatenetwork.io:34000", "http://2.bvn0.testnet.accumulatenetwork.io:34000", "http://0.bvn1.testnet.accumulatenetwork.io:34000", "http://1.bvn1.testnet.accumulatenetwork.io:34000", "http://2.bvn1.testnet.accumulatenetwork.io:34000", "http://0.bvn2.testnet.accumulatenetwork.io:34000", "http://1.bvn2.testnet.accumulatenetwork.io:34000", "http://2.bvn2.testnet.accumulatenetwork.io:34000"]
    SEED = ["http://0.bvn2.testnet.accumulatenetwork.io:26656"]

[website]
  website-enabled = false
  website-listen-address = "http://0.0.0.0:8080"
