package api

// GENERATED BY go run ./tools/cmd/gen-enum. DO NOT EDIT.

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ErrorCodeOk .
const ErrorCodeOk ErrorCode = 0

// ErrorCodeNotFound .
const ErrorCodeNotFound ErrorCode = 1

// ErrorCodeAlreadyExists .
const ErrorCodeAlreadyExists ErrorCode = 2

// GetEnumValue returns the value of the Error Code
func (v ErrorCode) GetEnumValue() uint64 { return uint64(v) }

// SetEnumValue sets the value. SetEnumValue returns false if the value is invalid.
func (v *ErrorCode) SetEnumValue(id uint64) bool {
	u := ErrorCode(id)
	switch u {
	case ErrorCodeOk, ErrorCodeNotFound, ErrorCodeAlreadyExists:
		*v = u
		return true
	default:
		return false
	}
}

// String returns the name of the Error Code.
func (v ErrorCode) String() string {
	switch v {
	case ErrorCodeOk:
		return "ok"
	case ErrorCodeNotFound:
		return "notFound"
	case ErrorCodeAlreadyExists:
		return "alreadyExists"
	default:
		return fmt.Sprintf("ErrorCode:%d", v)
	}
}

// ErrorCodeByName returns the named Error Code.
func ErrorCodeByName(name string) (ErrorCode, bool) {
	switch strings.ToLower(name) {
	case "ok":
		return ErrorCodeOk, true
	case "notfound":
		return ErrorCodeNotFound, true
	case "alreadyexists":
		return ErrorCodeAlreadyExists, true
	default:
		return 0, false
	}
}

// MarshalJSON marshals the Error Code to JSON as a string.
func (v ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.String())
}

// UnmarshalJSON unmarshals the Error Code from JSON as a string.
func (v *ErrorCode) UnmarshalJSON(data []byte) error {
	var s string
	err := json.Unmarshal(data, &s)
	if err != nil {
		return err
	}

	var ok bool
	*v, ok = ErrorCodeByName(s)
	if !ok || strings.ContainsRune(v.String(), ':') {
		return fmt.Errorf("invalid Error Code %q", s)
	}
	return nil
}
