include:
- local: /.gitlab/common.gitlab-ci.yml
- local: /.gitlab/all.gitlab-ci.yml
- local: /.gitlab/merge-request.gitlab-ci.yml
- local: /.gitlab/release.gitlab-ci.yml
- template: Jobs/License-Scanning.gitlab-ci.yml
- template: Jobs/Dependency-Scanning.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml
- template: Jobs/SAST.gitlab-ci.yml

license_scanning:
  rules:
  - if: $CI_PIPELINE_SOURCE

gemnasium-dependency_scanning:
  rules:
  - if: $CI_PIPELINE_SOURCE
  - if: $DEPENDENCY_SCANNING_DISABLED
    when: never

secret_detection:
  rules:
  - if: $CI_PIPELINE_SOURCE
  - if: $SECRET_DETECTION_DISABLED
    when: never

semgrep-sast:
  rules:
  - if: $CI_PIPELINE_SOURCE
  - if: $SAST_DISABLED
    when: never
