# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- local: "/ci/common.gitlab-ci.yml"
- local: "/ci/all.gitlab-ci.yml"
- local: "/ci/merge-request.gitlab-ci.yml"
- local: "/ci/release.gitlab-ci.yml"
- template: Security/SAST.gitlab-ci.yml
stages:
- test
sast:
  stage: test
