stages:
- test
- build
- deploy

.test:
  stage: test
  tags:
  - docker
  - linux
  script:
  - go build ./...
  - go test ./...

test go1.16:
  extends: .test
  image: golang:1.16

test go1.17:
  extends: .test
  image: golang:1.17

git describe:
  stage: test
  tags:
  - docker
  - linux
  script:
  - git fetch --unshallow
  - echo "GIT_DESCRIBE=$(git describe --dirty)" >> git.env
  artifacts:
    reports:
      dotenv: git.env

build:
  stage: build
  tags:
  - docker
  - linux
  image: golang:1.17
  before_script:
  - |
    function build {
      export GOOS=$1
      export GOARCH=$2
      BIN=accumulated-${GOOS}-${GOARCH}
      [ $GOOS == windows ] && BIN=${BIN}.exe
      export BUILDFLAGS="-o ${BIN}"
      echo Build $BIN
      make GIT_COMMIT=${CI_COMMIT_SHA} GIT_DESCRIBE=${GIT_DESCRIBE}
    }
  script:
  - build linux amd64
  - build linux arm64
  - build windows amd64
  - build windows arm64
  - build darwin amd64
  - build darwin arm64
  artifacts:
    paths:
    - accumulated-*

configure:
  stage: build
  tags:
  - docker
  - linux
  image: golang:1.17
  script:
  - |
    function init {
      rm -rf .nodes
      ./accumulated init -w .nodes --no-empty-blocks -r Arches,AmericanSamoa,EastXeons -n $1
      tar czf config-$1.tar.gz -C .nodes .
    }
  - go build ./cmd/accumulated
  - init Arches
  - init AmericanSamoa
  - init EastXeons
  artifacts:
    paths:
    - config-*.tar.gz

.deploy:
  stage: deploy
  only:
  - develop # only run on the main branch
  tags:
  - docker
  - linux
  script:
  - mkdir ~/.ssh
  - cp ${SSH_KNOWN_HOSTS} ~/.ssh/known_hosts
  - cp ${SSH_PRIV_KEY} ~/.ssh/id_rsa
  - cp ${SSH_PUB_KEY} ~/.ssh/id_rsa.pub
  - chmod -R 600 ~/.ssh
  - scp ${BIN} ec2-user@${HOST}:accumulated-latest
  - scp config-${NETWORK}.tar.gz ec2-user@${HOST}:config.tar.gz
  - ssh ec2-user@${HOST} '~/accumulated-latest version'
  - varname=DEPLOY_${NETWORK}_${NODE}
  - echo ${varname}=${!varname}
  - |
    if [ "${!varname}" = "yes" ]; then ssh ec2-user@${HOST} "
      set -ex
      export PATH="'"$PATH:$HOME/.local/bin"'"
      screen -ls | grep '\baccumulated\b' && screen -S accumulated -X stuff ^C
      rm -f ~/.local/bin/accumulated
      mv accumulated-latest ~/.local/bin/accumulated
      rm -rf ~/.accumulate
      mkdir ~/.accumulate
      tar xf config.tar.gz -C ~/.accumulate
      screen -d -m -S accumulated accumulated run -n ${NODE}
    "; fi

deploy 13.51.10.110:
  extends: .deploy
  variables:   { HOST: 13.51.10.110,                NETWORK: Arches,          NODE: 0, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://13.51.10.110:8080',   name: Arches/Node0 }

deploy 13.232.230.216:
  extends: .deploy
  variables:   { HOST: 13.232.230.216,              NETWORK: Arches,          NODE: 1, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://13.232.230.216:8080', name: Arches/Node1 }

deploy 18.221.39.36:
  extends: .deploy
  variables:   { HOST: 18.221.39.36,                NETWORK: AmericanSamoa,   NODE: 0, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://18.221.39.36:8080',   name: AmericanSamoa/Node0 }

deploy 44.236.45.58:
  extends: .deploy
  variables:   { HOST: 44.236.45.58,                NETWORK: AmericanSamoa,   NODE: 1, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://44.236.45.58:8080',   name: AmericanSamoa/Node1 }

deploy 18.119.26.7:
  extends: .deploy
  variables:   { HOST: 18.119.26.7,                 NETWORK: EastXeons,       NODE: 0, BIN: accumulated-linux-amd64 }
  environment: { url: 'http://18.119.26.7:8080',    name: EastXeons/Node0 }

deploy 18.119.149.208:
  extends: .deploy
  variables:   { HOST: 18.119.149.208,              NETWORK: EastXeons,       NODE: 1, BIN: accumulated-linux-amd64 }
  environment: { url: 'http://18.119.149.208:8080', name: EastXeons/Node1 }
