include:
- local: /.gitlab/common.gitlab-ci.yml
- local: /.gitlab/all.gitlab-ci.yml
- local: /.gitlab/merge-request.gitlab-ci.yml
- local: /.gitlab/release.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml