linters:
  enable:
  - noprint
  - nodebug
  - rangevarref

  disable:
  # TODO Enable these and fix the issues
  - staticcheck
  - gosimple

  # TODO Disabled due to http://github.com/golangci/golangci-lint/issues/2859
  - unused

issues:
  max-same-issues: 0

  exclude-rules:
  - path: cmd|tools/test
    linters:
    - noprint

  - path: .*_test\.go
    linters:
    - noprint

  - path: smt/.*/RandHash\.go
    linters:
    - noprint