linters:
  enable:
  - noprint

issues:
  exclude-rules:
  - path: cmd|tools/test
    linters:
    - noprint

  - path: .*_test\.go
    linters:
    - noprint

  - path: smt/.*/RandHash\.go
    linters:
    - noprint