linters-settings:
  custom:
    noprint:
      type: module
    nodebug:
      type: module
    rangevarref:
      type: module

  goheader:
    values:
      const:
        AUTHOR: The Accumulate Authors
    template: |-
      Copyright {{ YEAR }} {{ AUTHOR }}

      Use of this source code is governed by an MIT-style
      license that can be found in the LICENSE file or at
      https://opensource.org/licenses/MIT.

linters:
  disable-all: true
  enable: [govet]

issues:
  max-same-issues: 0

  exclude-rules:
  - path: cmd|test/cmd
    linters:
    - noprint

  - path: ^test/|.*_test\.go
    linters:
    - noprint
    - gosec

  - path: smt/.*/RandHash\.go
    linters:
    - noprint

  - path: _gen.go$
    linters:
    - goheader
    - gosimple

  - path: ^test/util/goroutine_leaks\.go$
    linters:
    - goheader
