linters:
  enable:
  - noprint
  - nodebug
  - rangevarref

  # TODO Enable these and fix the issues
  disable:
  - staticcheck
  - gosimple

issues:
  max-same-issues: 0

  exclude-rules:
  - path: cmd|tools/test
    linters:
    - noprint

  - path: .*_test\.go
    linters:
    - noprint

  - path: smt/.*/RandHash\.go
    linters:
    - noprint