linters:
  disable-all: true
  enable:
  # Custom
  - noprint # Use forbidigo instead?
  - nodebug
  - rangevarref

  # Standard
  - asasalint     # Bugs (variadic functions taking any)
  - bidichk       # Check for questionable Unicode
  - exportloopref # Smarter version of rangevarref?
  - goheader      # Enforce the copyright header
  - maintidx      # Maintainability
  - misspell      # Spelling
  - nakedret      # Not really sure what this one does
  - unconvert     # Lint (unnecessary conversions)

  # Gosec panics on some of the generic code
  # - gosec         # Security
  # - nilerr        # Bugs (error checking)

  # Defaults
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused

  # - nestif # I'd like to enable this but I don't want to deal with the issues yet
  # - godox # Enable to find TODO/BUG/FIXME

issues:
  max-same-issues: 0

  exclude-rules:
  - path: cmd|test/cmd
    linters:
    - noprint

  - path: ^test/|.*_test\.go
    linters:
    - noprint
    - gosec

  - path: smt/.*/RandHash\.go
    linters:
    - noprint

  # TODO Reduce the complexity of these functions so they pass
  - { source: func \(m \*Executor\) EndBlock,            linters: [maintidx]}
  - { source: func \(x \*Executor\) executeEnvelope,     linters: [maintidx]}
  - { source: func \(x \*Executor\) processSignature,    linters: [maintidx]}
  - { source: func \(m \*JrpcMethods\) Query,            linters: [maintidx]}
  - { source: func TestTransactionIsReady,               linters: [maintidx]}
  - { source: func \(s \*ValidationTestSuite\) TestMain, linters: [maintidx]}
  - { source: func \(n \*Node\) execute,                 linters: [maintidx]}
  - { source: func \(block \*Block\) Close,              linters: [maintidx]}

linters-settings:
  goheader:
    values:
      const:
        AUTHOR: The Accumulate Authors
    template: |-
      Copyright {{ YEAR }} {{ AUTHOR }}

      Use of this source code is governed by an MIT-style
      license that can be found in the LICENSE file or at
      https://opensource.org/licenses/MIT.