linters:
  enable:
  - noprint
  - nodebug
  - rangevarref

  disable:
  - structcheck # https://github.com/golangci/golangci-lint/issues/2649

issues:
  max-same-issues: 0

  exclude-rules:
  - path: cmd|tools/test
    linters:
    - noprint

  - path: .*_test\.go
    linters:
    - noprint

  - path: smt/.*/RandHash\.go
    linters:
    - noprint