output: test/mocks
case: underscore
recursive: true
keeptree: true
with-expecter: true
name: ^(NodeService|ConsensusService|NetworkService|MetricsService|Querier|Submitter|Validator|EventService|Sequencer)$