FROM golang:1.17 as build

# Build
WORKDIR /root
COPY . .
ENV CGO_ENABLED 0
RUN make && make cli

FROM alpine:3

# Copy binary
COPY --from=build /root/cli /root/accumulated /bin/

RUN apk add --no-cache bash jq curl
WORKDIR /scripts
COPY scripts .

CMD ["cli"]