directory = "tcp://127.0.1.1"
network = "LocalDevNet"
networks = ["tcp://127.0.1.2:26657"]
sentry-dsn = "https://glet_78c3bf45d009794a4d9b0c990a1f1ed5@gitlab.com/api/v4/error_tracking/collector/29762666"
type = "block-validator"
website-enabled = false
website-listen-address = "tcp://127.0.1.2:8080"

[api]
  debug-jsonrpc = false
  enable-subscribe-tx = false
  json-listen-address = "tcp://127.0.1.2:26660"
  prometheus-server = "http://18.119.26.7:9090"
  rest-listen-address = "tcp://127.0.1.2:26661"
  tx-max-wait-time = "10s"
