mr bott:
  stage: test
  needs: []
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PROJECT: $CI_PROJECT_PATH
    MERGE_REQUEST: $CI_MERGE_REQUEST_IID
  trigger: accumulatenetwork/core/gitlab-bot