.rules release:
  rules:
  - if: ($CI_COMMIT_BRANCH == 'release-1.0' || $CI_COMMIT_TAG != null) && $CI_PIPELINE_SOURCE != 'merge_request_event'

git describe:
  stage: pre deploy
  extends: .rules all
  needs: []
  script:
  - git fetch --unshallow
  - echo "GIT_DESCRIBE=$(git describe --dirty)" >> git.env
  artifacts:
    reports:
      dotenv: git.env

docker buildx:
  stage: pre deploy
  extends: .rules release
  image: docker:20-git
  needs: []
  variables:
    GIT_STRATEGY: none
  artifacts:
    paths:
      - buildx
    expire_in: 1 day
  services: [ docker:20-dind ]
  script:
    - export DOCKER_BUILDKIT=1
    - git clone https://github.com/docker/buildx ./docker-buildx
    - docker build --platform=local -o . ./docker-buildx

build main image:
  stage: pre deploy
  extends: .rules release
  needs: [ docker buildx ]
  image: docker:20
  timeout: 2 hours
  services:
    - name: docker:20-dind
      command: [ --experimental ] # Do we need this?
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  script:
    - GIT_DESCRIBE=$(git fetch --tags -q ; git describe --dirty)
    - GIT_COMMIT=$(shell git rev-parse HEAD)
    - docker buildx create --use
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build --platform linux/amd64,linux/arm64 --push --build-arg "GIT_DESCRIBE=$(GIT_DESCRIBE)" --build-arg "GIT_COMMIT=$(GIT_COMMIT)" -t ${PRODUCTION_IMAGE} .

build binaries:
  stage: pre deploy
  extends: [ .rules release, .go ]
  needs: [ git describe ]
  # rules:
  # - if: ($CI_COMMIT_BRANCH != 'develop' && $CI_COMMIT_TAG == null) || $CI_PIPELINE_SOURCE == 'merge_request_event'
  #   when: manual
  script:
    - build-daemon linux amd64
    - build-daemon linux arm64
    - build-daemon windows amd64
    - build-daemon windows arm64
    - build-daemon darwin amd64
    - build-daemon darwin arm64
  artifacts:
    paths:
      - accumulated-*
