[semgrep]

  # This rule complains if Mkdir/MkdirAll is called with mode > 0600 and !=
  # 0750, which is stupid so I'm disabling it.
  [[semgrep.ruleset]]
    disable = true
    [semgrep.ruleset.identifier]
      type = "semgrep_id"
      value = "gosec.G301-1"

  # This rule is complaining about path traversal. I don't see how that is at
  # all relevant to Accumulate so I'm disabling it.
  [[semgrep.ruleset]]
    disable = true
    [semgrep.ruleset.identifier]
      type = "semgrep_id"
      value = "gosec.G304-1"