[semgrep]
  [[semgrep.ruleset]]
    disable = true
    [semgrep.ruleset.identifier]
      # This rule complains if Mkdir/MkdirAll is called with mode > 0600 and !=
      # 0750, which is stupid so I'm disabling it
      type = "semgrep_id"
      value = "gosec.G301-1"