include:
- template: Jobs/Dependency-Scanning.gitlab-ci.yml
- template: Jobs/SAST.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml

gemnasium-dependency_scanning:
  rules:
  - if: $CI_PIPELINE_SOURCE

semgrep-sast:
  rules:
  - if: $CI_PIPELINE_SOURCE

secret_detection:
  rules:
  - if: $CI_PIPELINE_SOURCE

code_intelligence:
  extends: [ .rules all, .go ]
  allow_failure: true
  script:
    - scip-go
    - scip convert
  artifacts:
    reports:
      lsif: dump.lsif
