
Describe:
  fields:
  - name: NetworkType
    toml: type
    type: NetworkType
    marshal-as: enum
  - name: PartitionId
    alternative: SubnetId
    toml: partition-id
    type: string
  - name: Advertise
    toml: advertise
    type: protocol.InternetAddress
    marshal-as: reference
    pointer: true
  - { name: LocalAddress, type: string, virtual: true, non-binary: true }
  - name: Network
    toml: network
    type: Network
    marshal-as: reference

Network:
  fields:
    - name: Id
      toml: id
      type: string
    - name: Seeds
      type: protocol.AddressBookEntry
      marshal-as: reference
      pointer: true
      repeatable: true
    - name: Ignore
      type: protocol.AddressBookEntry
      marshal-as: reference
      pointer: true
      repeatable: true
    - name: Partitions
      alternative: Subnets
      toml: partitions
      type: Partition
      marshal-as: reference
      repeatable: true

Partition:
  fields:
    - name: Id
      toml: id
      type: string
    - name: Type
      toml: type
      type: NetworkType
      marshal-as: enum
    - name: BasePort
      toml: port
      type: int
    - name: Nodes
      toml: nodes
      type: Node
      marshal-as: reference
      repeatable: true

Node:
  fields:
    - name: Address
      toml: address
      type: protocol.InternetAddress
      marshal-as: reference
      pointer: true
    - name: PublicKey
      toml: public-key
      type: bytes

