
Describe:
  fields:
  - name: NetworkType
    toml: type
    type: NetworkType
    marshal-as: enum
  - name: PartitionId
    alternative: SubnetId
    toml: partition-id
    type: string
  - name: LocalAddress
    toml: local-address
    type: string
  - name: Network
    toml: network
    type: Network
    marshal-as: reference

Network:
  fields:
    - name: Id
      toml: id
      type: string
    - name: Partitions
      alternative: Subnets
      toml: partitions
      type: Partition
      marshal-as: reference
      repeatable: true

Partition:
  fields:
    - name: Id
      toml: id
      type: string
    - name: Type
      toml: type
      type: NetworkType
      marshal-as: enum
    - name: BasePort
      toml: port
      type: int
    - name: Nodes
      toml: nodes
      type: Node
      marshal-as: reference
      repeatable: true

Node:
  fields:
    - name: Address
      toml: address
      type: string
    - name: Type
      toml: type
      type: NodeType
      marshal-as: enum

