Describe:
  fields:
  - name: NetworkType
    toml: type
    type: NetworkType
    marshal-as: enum
  - name: NetworkId
    toml: network-id
    type: string
  - name: PartitionId
    alternative: SubnetId
    toml: partition-id
    type: string
