Network:
  non-binary: true
  fields:
    - name: NetworkName
      toml: network-name
      type: string
    - name: Type
      toml: type
      type: NetworkType
      marshal-as: enum
    - name: LocalPartitionID
      alternative: LocalSubnetID
      toml: local-partition
      type: string
    - name: LocalAddress
      toml: local-address
      type: string
    - name: Partitions
      alternative: Subnets
      toml: partitions
      type: Partition
      marshal-as: reference
      repeatable: true

Partition:
  non-binary: true
  fields:
    - name: ID
      toml: id
      type: string
    - name: Type
      toml: type
      type: NetworkType
      marshal-as: enum
    - name: Nodes
      toml: nodes
      type: Node
      marshal-as: reference
      repeatable: true

Node:
  non-binary: true
  fields:
    - name: Address
      toml: address
      type: string
    - name: Type
      toml: type
      type: NodeType
      marshal-as: enum