// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	DBVCInstructionHeader
	BVCEntry
	Submission
	BVCEntryResponse
	ValRequest
	ValReponse
	Entry
	Height
	EntryBytes
	Account
	Group
	AccountAdd
	GasAllowanceUpdate
	Reply
	KeyValue
	Key
	NodeInfo
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DBVCInstructionHeaderInsType int32

const (
	DBVCInstructionHeader_Unknown             DBVCInstructionHeaderInsType = 0
	DBVCInstructionHeader_EntrySubmit         DBVCInstructionHeaderInsType = 1
	DBVCInstructionHeader_EntryReveal         DBVCInstructionHeaderInsType = 2
	DBVCInstructionHeader_AddChain            DBVCInstructionHeaderInsType = 3
	DBVCInstructionHeader_RemoveChain         DBVCInstructionHeaderInsType = 4
	DBVCInstructionHeader_RegisterMasterChain DBVCInstructionHeaderInsType = 5
	DBVCInstructionHeader_RemoveMasterChain   DBVCInstructionHeaderInsType = 6
	DBVCInstructionHeader_RegisterADI         DBVCInstructionHeaderInsType = 7
)

var DBVCInstructionHeaderInsType_name = map[int32]string{
	0: "Unknown",
	1: "EntrySubmit",
	2: "EntryReveal",
	3: "AddChain",
	4: "RemoveChain",
	5: "RegisterMasterChain",
	6: "RemoveMasterChain",
	7: "RegisterADI",
}
var DBVCInstructionHeaderInsType_value = map[string]int32{
	"Unknown":             0,
	"EntrySubmit":         1,
	"EntryReveal":         2,
	"AddChain":            3,
	"RemoveChain":         4,
	"RegisterMasterChain": 5,
	"RemoveMasterChain":   6,
	"RegisterADI":         7,
}

func (x DBVCInstructionHeaderInsType) String() string {
	return proto1.EnumName(DBVCInstructionHeaderInsType_name, int32(x))
}
func (DBVCInstructionHeaderInsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type EntryMsgType int32

const (
	Entry_WriteEntryBytes    EntryMsgType = 0
	Entry_WriteKeyValue      EntryMsgType = 1
	Entry_ReadKeyValue       EntryMsgType = 2
	Entry_AccountWrite       EntryMsgType = 100
	Entry_AccountRead        EntryMsgType = 101
	Entry_GasAllowanceUpdate EntryMsgType = 105
)

var EntryMsgType_name = map[int32]string{
	0:   "WriteEntryBytes",
	1:   "WriteKeyValue",
	2:   "ReadKeyValue",
	100: "AccountWrite",
	101: "AccountRead",
	105: "GasAllowanceUpdate",
}
var EntryMsgType_value = map[string]int32{
	"WriteEntryBytes":    0,
	"WriteKeyValue":      1,
	"ReadKeyValue":       2,
	"AccountWrite":       100,
	"AccountRead":        101,
	"GasAllowanceUpdate": 105,
}

func (x EntryMsgType) String() string {
	return proto1.EnumName(EntryMsgType_name, int32(x))
}
func (EntryMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

// Directory Block Validation Chain (DBVC) Instruction Header
// maybe rethink into instruction and subcommand.  for example entry has several froms as does chain, adi etc.
// the chain address routes the thing anyway so maybe instruction really needs to be address
type DBVCInstructionHeader struct {
	Instruction        DBVCInstructionHeaderInsType `protobuf:"varint,1,opt,name=instruction,enum=apiProto.DBVCInstructionHeaderInsType" json:"instruction,omitempty"`
	Version            uint32                       `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	BvcMasterChainDDII []byte                       `protobuf:"bytes,3,opt,name=bvcMasterChainDDII,proto3" json:"bvcMasterChainDDII,omitempty"`
	BvcValidatorDDII   []byte                       `protobuf:"bytes,4,opt,name=bvcValidatorDDII,proto3" json:"bvcValidatorDDII,omitempty"`
}

func (m *DBVCInstructionHeader) Reset()                    { *m = DBVCInstructionHeader{} }
func (m *DBVCInstructionHeader) String() string            { return proto1.CompactTextString(m) }
func (*DBVCInstructionHeader) ProtoMessage()               {}
func (*DBVCInstructionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DBVCInstructionHeader) GetInstruction() DBVCInstructionHeaderInsType {
	if m != nil {
		return m.Instruction
	}
	return DBVCInstructionHeader_Unknown
}

func (m *DBVCInstructionHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DBVCInstructionHeader) GetBvcMasterChainDDII() []byte {
	if m != nil {
		return m.BvcMasterChainDDII
	}
	return nil
}

func (m *DBVCInstructionHeader) GetBvcValidatorDDII() []byte {
	if m != nil {
		return m.BvcValidatorDDII
	}
	return nil
}

type BVCEntry struct {
	Header *DBVCInstructionHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Entry  []byte                 `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	//  header := [ version (1byte) | varintf ddiilen | ddii (up to 32 bytes) ]
	//  body :=   [  bvc bigendian blockheight (4 bytes) |
	//               unix timestamp (4 bytes) |
	//               Merkel DAG Root hash (32 Bytes)]
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *BVCEntry) Reset()                    { *m = BVCEntry{} }
func (m *BVCEntry) String() string            { return proto1.CompactTextString(m) }
func (*BVCEntry) ProtoMessage()               {}
func (*BVCEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BVCEntry) GetHeader() *DBVCInstructionHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BVCEntry) GetEntry() []byte {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *BVCEntry) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Submission struct {
	Address     uint64 `protobuf:"varint,1,opt,name=address" json:"address,omitempty"`
	Class       uint32 `protobuf:"varint,2,opt,name=class" json:"class,omitempty"`
	Instruction uint32 `protobuf:"varint,3,opt,name=instruction" json:"instruction,omitempty"`
	Param1      uint64 `protobuf:"varint,4,opt,name=param1" json:"param1,omitempty"`
	Param2      uint64 `protobuf:"varint,5,opt,name=param2" json:"param2,omitempty"`
	Data        []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Submission) Reset()                    { *m = Submission{} }
func (m *Submission) String() string            { return proto1.CompactTextString(m) }
func (*Submission) ProtoMessage()               {}
func (*Submission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Submission) GetAddress() uint64 {
	if m != nil {
		return m.Address
	}
	return 0
}

func (m *Submission) GetClass() uint32 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *Submission) GetInstruction() uint32 {
	if m != nil {
		return m.Instruction
	}
	return 0
}

func (m *Submission) GetParam1() uint64 {
	if m != nil {
		return m.Param1
	}
	return 0
}

func (m *Submission) GetParam2() uint64 {
	if m != nil {
		return m.Param2
	}
	return 0
}

func (m *Submission) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BVCEntryResponse struct {
	ResponseData []byte `protobuf:"bytes,1,opt,name=responseData,proto3" json:"responseData,omitempty"`
	ErrorCode    uint64 `protobuf:"varint,2,opt,name=errorCode" json:"errorCode,omitempty"`
}

func (m *BVCEntryResponse) Reset()                    { *m = BVCEntryResponse{} }
func (m *BVCEntryResponse) String() string            { return proto1.CompactTextString(m) }
func (*BVCEntryResponse) ProtoMessage()               {}
func (*BVCEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BVCEntryResponse) GetResponseData() []byte {
	if m != nil {
		return m.ResponseData
	}
	return nil
}

func (m *BVCEntryResponse) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type ValRequest struct {
	ValidatorAddr uint64 `protobuf:"varint,1,opt,name=validatorAddr" json:"validatorAddr,omitempty"`
	Instruction   uint32 `protobuf:"varint,2,opt,name=instruction" json:"instruction,omitempty"`
	Parameter1    uint32 `protobuf:"varint,3,opt,name=parameter1" json:"parameter1,omitempty"`
	Parameter2    uint32 `protobuf:"varint,4,opt,name=parameter2" json:"parameter2,omitempty"`
	Nonce         uint64 `protobuf:"varint,5,opt,name=nonce" json:"nonce,omitempty"`
	Data          []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Signed        []byte `protobuf:"bytes,7,opt,name=signed,proto3" json:"signed,omitempty"`
}

func (m *ValRequest) Reset()                    { *m = ValRequest{} }
func (m *ValRequest) String() string            { return proto1.CompactTextString(m) }
func (*ValRequest) ProtoMessage()               {}
func (*ValRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValRequest) GetValidatorAddr() uint64 {
	if m != nil {
		return m.ValidatorAddr
	}
	return 0
}

func (m *ValRequest) GetInstruction() uint32 {
	if m != nil {
		return m.Instruction
	}
	return 0
}

func (m *ValRequest) GetParameter1() uint32 {
	if m != nil {
		return m.Parameter1
	}
	return 0
}

func (m *ValRequest) GetParameter2() uint32 {
	if m != nil {
		return m.Parameter2
	}
	return 0
}

func (m *ValRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ValRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ValRequest) GetSigned() []byte {
	if m != nil {
		return m.Signed
	}
	return nil
}

type ValReponse struct {
	ResponseData []byte `protobuf:"bytes,1,opt,name=responseData,proto3" json:"responseData,omitempty"`
	ErrorCode    uint64 `protobuf:"varint,2,opt,name=errorCode" json:"errorCode,omitempty"`
}

func (m *ValReponse) Reset()                    { *m = ValReponse{} }
func (m *ValReponse) String() string            { return proto1.CompactTextString(m) }
func (*ValReponse) ProtoMessage()               {}
func (*ValReponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ValReponse) GetResponseData() []byte {
	if m != nil {
		return m.ResponseData
	}
	return nil
}

func (m *ValReponse) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type Entry struct {
	Key         []byte       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MessageType EntryMsgType `protobuf:"varint,2,opt,name=messageType,enum=apiProto.EntryMsgType" json:"messageType,omitempty"`
	Nonce       uint64       `protobuf:"varint,3,opt,name=nonce" json:"nonce,omitempty"`
	Data        []byte       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Signed      []byte       `protobuf:"bytes,5,opt,name=signed,proto3" json:"signed,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto1.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Entry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetMessageType() EntryMsgType {
	if m != nil {
		return m.MessageType
	}
	return Entry_WriteEntryBytes
}

func (m *Entry) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Entry) GetSigned() []byte {
	if m != nil {
		return m.Signed
	}
	return nil
}

type Height struct {
	Height uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *Height) Reset()                    { *m = Height{} }
func (m *Height) String() string            { return proto1.CompactTextString(m) }
func (*Height) ProtoMessage()               {}
func (*Height) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Height) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EntryBytes struct {
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *EntryBytes) Reset()                    { *m = EntryBytes{} }
func (m *EntryBytes) String() string            { return proto1.CompactTextString(m) }
func (*EntryBytes) ProtoMessage()               {}
func (*EntryBytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EntryBytes) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Account struct {
	Name             string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Owner            string           `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
	MessageAllowance int32            `protobuf:"varint,3,opt,name=messageAllowance" json:"messageAllowance,omitempty"`
	Groups           []*Account_Group `protobuf:"bytes,4,rep,name=groups" json:"groups,omitempty"`
	AllowAddAccounts bool             `protobuf:"varint,5,opt,name=allowAddAccounts" json:"allowAddAccounts,omitempty"`
	AllowAddGroups   bool             `protobuf:"varint,6,opt,name=allowAddGroups" json:"allowAddGroups,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto1.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Account) GetMessageAllowance() int32 {
	if m != nil {
		return m.MessageAllowance
	}
	return 0
}

func (m *Account) GetGroups() []*Account_Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Account) GetAllowAddAccounts() bool {
	if m != nil {
		return m.AllowAddAccounts
	}
	return false
}

func (m *Account) GetAllowAddGroups() bool {
	if m != nil {
		return m.AllowAddGroups
	}
	return false
}

type Account_Group struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	AdminRights bool   `protobuf:"varint,2,opt,name=adminRights" json:"adminRights,omitempty"`
}

func (m *Account_Group) Reset()                    { *m = Account_Group{} }
func (m *Account_Group) String() string            { return proto1.CompactTextString(m) }
func (*Account_Group) ProtoMessage()               {}
func (*Account_Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *Account_Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account_Group) GetAdminRights() bool {
	if m != nil {
		return m.AdminRights
	}
	return false
}

type Group struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto1.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AccountAdd struct {
	PublicKey []byte   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Account   *Account `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
}

func (m *AccountAdd) Reset()                    { *m = AccountAdd{} }
func (m *AccountAdd) String() string            { return proto1.CompactTextString(m) }
func (*AccountAdd) ProtoMessage()               {}
func (*AccountAdd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AccountAdd) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *AccountAdd) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GasAllowanceUpdate struct {
	AccountKey   []byte `protobuf:"bytes,1,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	GasAllowance int32  `protobuf:"varint,2,opt,name=gasAllowance" json:"gasAllowance,omitempty"`
}

func (m *GasAllowanceUpdate) Reset()                    { *m = GasAllowanceUpdate{} }
func (m *GasAllowanceUpdate) String() string            { return proto1.CompactTextString(m) }
func (*GasAllowanceUpdate) ProtoMessage()               {}
func (*GasAllowanceUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GasAllowanceUpdate) GetAccountKey() []byte {
	if m != nil {
		return m.AccountKey
	}
	return nil
}

func (m *GasAllowanceUpdate) GetGasAllowance() int32 {
	if m != nil {
		return m.GasAllowance
	}
	return 0
}

type Reply struct {
	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height uint64 `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto1.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Reply) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Reply) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Reply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type KeyValue struct {
	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Height uint64 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto1.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Key struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto1.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type NodeInfo struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto1.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto1.RegisterType((*DBVCInstructionHeader)(nil), "apiProto.DBVCInstructionHeader")
	proto1.RegisterType((*BVCEntry)(nil), "apiProto.BVCEntry")
	proto1.RegisterType((*Submission)(nil), "apiProto.Submission")
	proto1.RegisterType((*BVCEntryResponse)(nil), "apiProto.BVCEntryResponse")
	proto1.RegisterType((*ValRequest)(nil), "apiProto.ValRequest")
	proto1.RegisterType((*ValReponse)(nil), "apiProto.ValReponse")
	proto1.RegisterType((*Entry)(nil), "apiProto.Entry")
	proto1.RegisterType((*Height)(nil), "apiProto.Height")
	proto1.RegisterType((*EntryBytes)(nil), "apiProto.EntryBytes")
	proto1.RegisterType((*Account)(nil), "apiProto.Account")
	proto1.RegisterType((*Account_Group)(nil), "apiProto.Account.Group")
	proto1.RegisterType((*Group)(nil), "apiProto.Group")
	proto1.RegisterType((*AccountAdd)(nil), "apiProto.AccountAdd")
	proto1.RegisterType((*GasAllowanceUpdate)(nil), "apiProto.GasAllowanceUpdate")
	proto1.RegisterType((*Reply)(nil), "apiProto.Reply")
	proto1.RegisterType((*KeyValue)(nil), "apiProto.KeyValue")
	proto1.RegisterType((*Key)(nil), "apiProto.Key")
	proto1.RegisterType((*NodeInfo)(nil), "apiProto.NodeInfo")
	proto1.RegisterEnum("apiProto.DBVCInstructionHeaderInsType", DBVCInstructionHeaderInsType_name, DBVCInstructionHeaderInsType_value)
	proto1.RegisterEnum("apiProto.EntryMsgType", EntryMsgType_name, EntryMsgType_value)
}

func init() { proto1.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1057 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0x1b, 0x37,
	0x13, 0xd6, 0xf9, 0x30, 0xb2, 0x9d, 0x0d, 0xe3, 0xc4, 0x82, 0xff, 0x1f, 0xad, 0x40, 0x04, 0xad,
	0xd1, 0x02, 0x6b, 0x44, 0x09, 0x10, 0x14, 0x45, 0x2f, 0x64, 0x3b, 0x70, 0x54, 0xa3, 0x41, 0xc0,
	0x24, 0x4e, 0xd1, 0x3b, 0x7a, 0x39, 0x91, 0x16, 0x91, 0x76, 0xb7, 0xe4, 0x4a, 0x86, 0x6e, 0xfa,
	0x18, 0x45, 0xaf, 0x9b, 0x77, 0xea, 0x8b, 0xf4, 0x05, 0x0a, 0xce, 0x72, 0xb5, 0x2b, 0x4b, 0x45,
	0x6e, 0x7a, 0x25, 0xce, 0xc7, 0x8f, 0x73, 0xf8, 0x38, 0x43, 0x2d, 0x74, 0x65, 0x12, 0xfa, 0x89,
	0x8e, 0xd3, 0x98, 0x75, 0x64, 0x12, 0xbe, 0xb6, 0xab, 0xe3, 0xff, 0x4d, 0xe2, 0x78, 0x32, 0xc3,
	0x53, 0xc2, 0x6f, 0x16, 0x1f, 0x4e, 0x71, 0x9e, 0xa4, 0xab, 0x8c, 0xc6, 0xff, 0xae, 0xc1, 0xc3,
	0x8b, 0xb3, 0xeb, 0xf3, 0x71, 0x64, 0x52, 0xbd, 0x08, 0xd2, 0x30, 0x8e, 0x5e, 0xa2, 0x54, 0xa8,
	0xd9, 0x18, 0x7a, 0x61, 0x01, 0xf6, 0xab, 0x83, 0xea, 0xc9, 0xc1, 0xf0, 0x6b, 0x3f, 0x77, 0xeb,
	0xef, 0x3c, 0xe5, 0x87, 0x91, 0x79, 0xbb, 0x4a, 0x50, 0x94, 0xcf, 0xb2, 0x3e, 0xb4, 0x97, 0xa8,
	0x8d, 0x75, 0x53, 0x1b, 0x54, 0x4f, 0xf6, 0x45, 0x6e, 0x32, 0x1f, 0xd8, 0xcd, 0x32, 0xf8, 0x49,
	0x9a, 0x14, 0xf5, 0xf9, 0x54, 0x86, 0xd1, 0xc5, 0xc5, 0x78, 0xdc, 0xaf, 0x0f, 0xaa, 0x27, 0x7b,
	0x62, 0xc7, 0x0e, 0xfb, 0x06, 0xbc, 0x9b, 0x65, 0x70, 0x2d, 0x67, 0xa1, 0x92, 0x69, 0xac, 0x89,
	0xdd, 0x20, 0xf6, 0x16, 0xce, 0xff, 0xa8, 0x42, 0xdb, 0xa5, 0xc3, 0x7a, 0xd0, 0x7e, 0x17, 0x7d,
	0x8c, 0xe2, 0xdb, 0xc8, 0xab, 0xb0, 0x7b, 0xd0, 0x7b, 0x11, 0xa5, 0x7a, 0xf5, 0x66, 0x71, 0x33,
	0x0f, 0x53, 0xaf, 0xba, 0x06, 0x04, 0x2e, 0x51, 0xce, 0xbc, 0x1a, 0xdb, 0x83, 0xce, 0x48, 0x29,
	0x0a, 0xeb, 0xd5, 0xed, 0xb6, 0xc0, 0x79, 0xbc, 0xc4, 0x0c, 0x68, 0xb0, 0x23, 0x78, 0x20, 0x70,
	0x12, 0xda, 0xd4, 0x4a, 0x09, 0x7a, 0x4d, 0xf6, 0x10, 0xee, 0x67, 0xcc, 0x32, 0xdc, 0xca, 0x1c,
	0x64, 0xfc, 0xd1, 0xc5, 0xd8, 0x6b, 0xf3, 0x5b, 0xe8, 0x9c, 0x5d, 0x9f, 0x53, 0x4c, 0xf6, 0x1c,
	0x5a, 0x53, 0xd2, 0x8e, 0x24, 0xee, 0x0d, 0xbf, 0xfc, 0x8c, 0xc4, 0xc2, 0xd1, 0xd9, 0x21, 0x34,
	0xd1, 0x7a, 0x20, 0x4d, 0xf7, 0x44, 0x66, 0xb0, 0xff, 0x43, 0xd7, 0x84, 0x93, 0x48, 0xa6, 0x0b,
	0x8d, 0x4e, 0xc8, 0x02, 0xe0, 0x7f, 0x56, 0x01, 0xa8, 0x6c, 0x63, 0xdc, 0xc5, 0x48, 0xa5, 0x34,
	0x1a, 0x43, 0xc1, 0x1b, 0x22, 0x37, 0xad, 0xf3, 0x60, 0x26, 0x8d, 0x71, 0x17, 0x96, 0x19, 0x6c,
	0xb0, 0xd9, 0x13, 0x75, 0xda, 0xdb, 0xb8, 0xea, 0x47, 0xd0, 0x4a, 0xa4, 0x96, 0xf3, 0x27, 0x74,
	0x2d, 0x0d, 0xe1, 0xac, 0x35, 0x3e, 0xec, 0x37, 0x4b, 0xf8, 0x90, 0x31, 0x68, 0x28, 0x99, 0xca,
	0x7e, 0x8b, 0x32, 0xa5, 0x35, 0x7f, 0x0b, 0x5e, 0xae, 0x8e, 0x40, 0x93, 0xc4, 0x91, 0x41, 0xc6,
	0x61, 0x4f, 0xbb, 0xf5, 0x85, 0xe5, 0x57, 0x89, 0xbf, 0x81, 0xd9, 0xd2, 0x51, 0xeb, 0x58, 0x9f,
	0xc7, 0x0a, 0x29, 0xef, 0x86, 0x28, 0x00, 0xfe, 0x57, 0x15, 0xe0, 0x5a, 0xce, 0x04, 0xfe, 0xba,
	0x40, 0x93, 0xb2, 0xc7, 0xb0, 0xbf, 0xcc, 0xdb, 0x65, 0xa4, 0x94, 0x76, 0x02, 0x6c, 0x82, 0x77,
	0x0b, 0xae, 0x6d, 0x17, 0xfc, 0x05, 0x00, 0x95, 0x82, 0x29, 0xea, 0x27, 0x4e, 0x91, 0x12, 0xb2,
	0xb1, 0x3f, 0x24, 0x51, 0xca, 0xfb, 0x43, 0x2b, 0x74, 0x14, 0x47, 0x01, 0x3a, 0x5d, 0x32, 0x63,
	0x97, 0x2c, 0x56, 0x42, 0x7b, 0x91, 0xa8, 0xfa, 0x6d, 0x42, 0x9d, 0xc5, 0x5f, 0xb9, 0xba, 0xfe,
	0x2b, 0xa1, 0x7e, 0xaf, 0x41, 0x33, 0x6b, 0x4d, 0x0f, 0xea, 0x1f, 0x71, 0xe5, 0x5c, 0xd8, 0x25,
	0xfb, 0x0e, 0x7a, 0x73, 0x34, 0x46, 0x4e, 0xd0, 0x8e, 0x15, 0x9d, 0x3d, 0x18, 0x1e, 0x15, 0x1d,
	0x4b, 0xe7, 0xfc, 0xb9, 0x99, 0x64, 0x8f, 0x40, 0x89, 0x5b, 0x14, 0x5a, 0xdf, 0x55, 0x68, 0x63,
	0x67, 0xa1, 0xcd, 0x8d, 0x42, 0x7f, 0x83, 0xb6, 0xf3, 0xcc, 0x1e, 0xc0, 0xbd, 0xf7, 0x3a, 0x4c,
	0x91, 0xe2, 0x9d, 0xad, 0x52, 0x34, 0x5e, 0x85, 0xdd, 0x87, 0x7d, 0x02, 0xaf, 0x70, 0x75, 0x2d,
	0x67, 0x0b, 0xf4, 0xaa, 0xcc, 0x83, 0x3d, 0x81, 0x52, 0xad, 0x91, 0x9a, 0x45, 0x46, 0x41, 0x10,
	0x2f, 0xa2, 0x94, 0xb8, 0x9e, 0xb2, 0xd3, 0xe9, 0x10, 0x4b, 0xf5, 0x90, 0x3d, 0x02, 0x76, 0x29,
	0xcd, 0x68, 0x36, 0x8b, 0x6f, 0x65, 0x14, 0xe0, 0xbb, 0x44, 0xc9, 0x14, 0xbd, 0x90, 0x0f, 0xa0,
	0xf5, 0x12, 0xc3, 0xc9, 0x34, 0xb5, 0x19, 0x4e, 0x69, 0xe5, 0xba, 0xc6, 0x59, 0x7c, 0x00, 0x50,
	0x64, 0x64, 0x6b, 0x2b, 0x5d, 0x01, 0xad, 0xf9, 0xa7, 0x1a, 0xb4, 0x5d, 0x34, 0xbb, 0x1f, 0xc9,
	0x39, 0xd2, 0x7e, 0x57, 0xd0, 0xda, 0xaa, 0x14, 0xdf, 0x46, 0xa8, 0x49, 0xda, 0xae, 0xc8, 0x0c,
	0xfb, 0xec, 0x39, 0x29, 0xd7, 0x59, 0x91, 0x8c, 0x4d, 0xb1, 0x85, 0xb3, 0x53, 0x68, 0x4d, 0x74,
	0xbc, 0x48, 0x4c, 0xbf, 0x31, 0xa8, 0x9f, 0xf4, 0xca, 0xb7, 0xe3, 0x02, 0xfb, 0x97, 0x76, 0x5f,
	0x38, 0x9a, 0x75, 0x2e, 0xed, 0xe9, 0x91, 0x52, 0x8e, 0x60, 0x48, 0xf8, 0x8e, 0xd8, 0xc2, 0xd9,
	0x57, 0x70, 0x90, 0x63, 0x97, 0x59, 0x90, 0x16, 0x31, 0xef, 0xa0, 0xc7, 0x3f, 0x40, 0x93, 0x56,
	0x3b, 0x6b, 0x1c, 0x40, 0x4f, 0xaa, 0x79, 0x18, 0x09, 0xab, 0x59, 0xf6, 0xc2, 0x74, 0x44, 0x19,
	0xe2, 0x9f, 0x3b, 0xae, 0xd0, 0x04, 0x3a, 0x4c, 0xd6, 0x33, 0xd9, 0x15, 0x65, 0x88, 0xbf, 0x07,
	0x70, 0x19, 0x8f, 0x94, 0xb2, 0xdd, 0x9e, 0x2c, 0x6e, 0x66, 0x61, 0x70, 0xb5, 0xee, 0xe5, 0x02,
	0x60, 0xdf, 0x42, 0x5b, 0x66, 0x5c, 0xf2, 0xd4, 0x1b, 0xde, 0xdf, 0xd2, 0x4b, 0xe4, 0x0c, 0xfe,
	0xf3, 0xae, 0xce, 0xb0, 0x23, 0xee, 0x08, 0x45, 0x84, 0x12, 0x62, 0x47, 0x72, 0x52, 0x3a, 0x45,
	0x71, 0x9a, 0x62, 0x03, 0xe3, 0x63, 0x68, 0x0a, 0x4c, 0x66, 0x2b, 0x5b, 0xf1, 0x54, 0x9a, 0x69,
	0xde, 0x34, 0x76, 0x5d, 0x6a, 0xb7, 0x5a, 0xb9, 0xdd, 0xe8, 0x1f, 0xc0, 0x8e, 0x2d, 0xf5, 0x42,
	0x57, 0x64, 0x06, 0xff, 0x11, 0x3a, 0x79, 0xbf, 0xef, 0x98, 0xe0, 0x43, 0x68, 0x2e, 0xed, 0x56,
	0xfe, 0xaf, 0x41, 0x46, 0x29, 0x42, 0x7d, 0xa3, 0xa1, 0x8f, 0xa0, 0x6e, 0x2b, 0xd8, 0x72, 0xc3,
	0x1f, 0x43, 0xe7, 0x55, 0xac, 0x70, 0x1c, 0x7d, 0x88, 0xcb, 0x7f, 0xef, 0xd9, 0x3d, 0xe5, 0xe6,
	0xf0, 0x53, 0x0d, 0x60, 0x94, 0x84, 0x6f, 0x50, 0x2f, 0xc3, 0x00, 0xd9, 0x33, 0xe8, 0xbe, 0x8e,
	0x4d, 0x9a, 0x3d, 0x2e, 0x87, 0x77, 0x5e, 0x0d, 0x9a, 0x99, 0xe3, 0x7b, 0x05, 0x4a, 0x7a, 0xf0,
	0x0a, 0x7b, 0xba, 0x39, 0xc3, 0x6c, 0xbf, 0xa0, 0x5c, 0xe1, 0xea, 0x98, 0x6d, 0x98, 0x44, 0xe1,
	0x15, 0xf6, 0x0c, 0x0e, 0xdc, 0x4b, 0x9f, 0x4f, 0xdb, 0x9d, 0x63, 0xdb, 0xd7, 0xcc, 0x2b, 0xec,
	0x39, 0x74, 0x2f, 0x31, 0xcd, 0x87, 0xdc, 0xcf, 0x3e, 0x9c, 0xfc, 0xfc, 0xc3, 0xc9, 0x7f, 0x61,
	0x3f, 0x9c, 0x8e, 0xbd, 0xe2, 0x64, 0xc6, 0xe4, 0x15, 0xf6, 0x3d, 0xf4, 0x2e, 0x31, 0x5d, 0x2b,
	0xf2, 0x6f, 0x47, 0x4b, 0xb9, 0xe6, 0x5c, 0x5e, 0x39, 0xeb, 0xfe, 0xd2, 0xf6, 0xdd, 0xd7, 0x59,
	0x8b, 0x7e, 0x9e, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xd7, 0xb4, 0x43, 0xc9, 0x09, 0x00,
	0x00,
}
