#!/bin/bash
# Deletion script for very old unmerged branches (1+ years)
# Generated: Wed Mar 25 06:00:16 PM CDT 2026

# WARNING: Review carefully before executing!
# Total branches to delete: 272

git push origin --delete 3148-executor-version
git push origin --delete 3151-regenesis
git push origin --delete 3199-new-txn-exec-framework
git push origin --delete 3199-update-create-account
git push origin --delete 3199-update-create-identity
git push origin --delete 3266-bpt-data-model
git push origin --delete 3267-integrate-bpt
git push origin --delete 3322-fix-sim
git push origin --delete 3379-better-anchor-healing-parallel
git push origin --delete 3384-database-sync-tool-updates
git push origin --delete 3495-bpt-backwards-compat
git push origin --delete 3539-unsigned-test-vectors
git push origin --delete 3565-eip712-ethan
git push origin --delete 3565-sign-typed-data-encoding
git push origin --delete 3570-generalize-pki-types
git push origin --delete 3588-blockchain-specific-key-value-database
git push origin --delete 3589-code-intelligence
git push origin --delete 3600-fee-schedule-consistency
git push origin --delete 3616-migrate-block-ledger
git push origin --delete 3617-instrumentation-followup
git push origin --delete 3621-csv2yaml
git push origin --delete 3623-backport
git push origin --delete 3626-expose-simulator
git push origin --delete 3640-mining-support
git push origin --delete 3640-mining-support-hmm
git push origin --delete 3644-csharp
git push origin --delete 39-dn-follower-node
git push origin --delete 4-staking-scaffolding-support
git push origin --delete AC-1031
git push origin --delete AC-1034-support-querying-lite-data-accounts-by-url-factom-jj
git push origin --delete AC-1042-Elucidation
git push origin --delete AC-1061
git push origin --delete AC-1080
git push origin --delete AC-1085-burn-acme-to-buy-credits-dhb
git push origin --delete AC-1086-aggregate-credit-burns-and-send-them-with-the-anchor
git push origin --delete AC-1089-only-charge-the-full-fee-once-a-transaction-is-promoted
git push origin --delete AC-1089-only-charge-the-full-fee-once-a-transaction-is-promoted-latest
git push origin --delete AC-1106
git push origin --delete AC-1106-ethan
git push origin --delete AC-1113
git push origin --delete AC-1118-add-func-to-return-a-range-of-chainids-state-hashes-and-states
git push origin --delete AC-1119-add-func-to-return-a-range-of-chainids-state-hashes-and-states
git push origin --delete AC-1133
git push origin --delete AC-1146-fix-validator-test
git push origin --delete AC-1188-remove-faucet
git push origin --delete AC-1193
git push origin --delete AC-1205-associate-different-signature-types-with-accounts-in-cli
git push origin --delete AC-1238
git push origin --delete AC-1244
git push origin --delete AC-1246-same-key
git push origin --delete AC-125-define-implement-the-query-parameters-within-abci
git push origin --delete AC-126
git push origin --delete AC-1278-add-network-endpoints
git push origin --delete AC-128-dockerfile
git push origin --delete AC-1290-fix-lazy-loading-of-the-bpt-root-node
git push origin --delete AC-1319-move-transaction-status-to-the-principal
git push origin --delete AC-1335-add-ecdsa-signature-support-cli
git push origin --delete AC-1338-key-parameter-needed
git push origin --delete AC-1350-flush-pending-writes
git push origin --delete AC-1398_dn-account-subnets
git push origin --delete AC-1420_query-anchored-dn-blocks
git push origin --delete AC-1424-human-readable-output-crashes-on-sendTokens
git push origin --delete AC-145
git push origin --delete AC-1468-generate-address
git push origin --delete AC-1471-compose-txn
git push origin --delete AC-1494-update-the-bpt-to-track-the-adis-of-accounts
git push origin --delete AC-1506-separate-api-backend
git push origin --delete AC-1529-stress-test
git push origin --delete AC-1597-node-status-update
git push origin --delete AC-1695-batch-adapter
git push origin --delete AC-1695-structured-cache
git push origin --delete AC-1710_snapshot-restore
git push origin --delete AC-1760-factom-snapshot-integration-ps
git push origin --delete AC-1761
git push origin --delete AC-188-anon-tx-history-subchains
git push origin --delete AC-200-cli
git push origin --delete AC-200-cli-queryfix
git push origin --delete AC-206_Refactor_Network
git push origin --delete AC-2072-accumulate-wallet-daemon
git push origin --delete AC-2148-data-model-chains
git push origin --delete AC-2234-many-cli-subcommands-accept-more-parameters-than-they-should
git push origin --delete AC-2434-revert-diff
git push origin --delete AC-250-basic-router
git push origin --delete AC-250-basic-router-tendermint-update
git push origin --delete AC-263-separate-out-bootstrap-network-configuration-files
git push origin --delete AC-265-load-test
git push origin --delete AC-2659-add-dual-mode-support-to-the-status-api-method
git push origin --delete AC-2807-add-debug-and-pprof-flags-to-run-dual
git push origin --delete AC-2810
git push origin --delete AC-2811
git push origin --delete AC-286-txhash-support
git push origin --delete AC-2872-wip
git push origin --delete AC-299-cleanup
git push origin --delete AC-3083_java_generator_fixes
git push origin --delete AC-3089-create-simulator-and-report-generator-for-staking
git push origin --delete AC-3124-encode-arbitrary-transaction-with-accumulate-walletd-jsonrpc-call
git push origin --delete AC-3132-all-api
git push origin --delete AC-3133-api-v3-initial
git push origin --delete AC-3134-query-service
git push origin --delete AC-3141-node-service
git push origin --delete AC-3146-factom-testnet-prevent-replay
git push origin --delete AC-3171-websocket-server
git push origin --delete AC-3172-event-service
git push origin --delete AC-3183-staking
git push origin --delete AC-3185_ledger-sign-send-tokens
git push origin --delete AC-3185_ledger-sign-send-tokens-after-cli-split
git push origin --delete AC-3190-staking-approval
git push origin --delete AC-3192-cli-bug-cli-is-supposed-to-debit-credits-from-key-page-2-but-it-uses-key-page-1-instead
git push origin --delete AC-3211-implement-interface
git push origin --delete AC-3226-staker-script
git push origin --delete AC-3230-service-router
git push origin --delete AC-3231-conn-mgr
git push origin --delete AC-3236-add-memo-walletd
git push origin --delete AC-3256-validate-walletd
git push origin --delete AC-3283-scan-deposits
git push origin --delete AC-3283-suggestions
git push origin --delete AC-337-fix-gen-tx
git push origin --delete AC-348-rename-gentx
git push origin --delete AC-388-add-error-reporting-for-batch-dispatch
git push origin --delete AC-422
git push origin --delete AC-444
git push origin --delete AC-463
git push origin --delete AC-479-index-entries-not-unique
git push origin --delete AC-509-alt
git push origin --delete AC-509-work
git push origin --delete AC-519-human-readable-output-for-tx
git push origin --delete AC-542-Unix-socket
git push origin --delete AC-544_state_db_readability_part2a
git push origin --delete AC-544_state_db_readability_part2b
git push origin --delete AC-544_state_db_readability_part3
git push origin --delete AC-558-Create-Unbound-Key-Page
git push origin --delete AC-574
git push origin --delete AC-630_basic-routing-framework
git push origin --delete AC-634
git push origin --delete AC-639-goSDK
git push origin --delete AC-662_Rename_to_LiteTokenAccount
git push origin --delete AC-697-protocol-recognition-when-lite-token-account-has-credits
git push origin --delete AC-726
git push origin --delete AC-749-lite-data-chain
git push origin --delete AC-756_advanced_routing_framework
git push origin --delete AC-757_ADI-directories
git push origin --delete AC-778-Prometheus
git push origin --delete AC-825
git push origin --delete AC-832-c-enums-generator
git push origin --delete AC-832-c-types-generator
git push origin --delete AC-888-Architecture-Documentation
git push origin --delete AC-925
git push origin --delete AC-972-keys-must-be-hashed-with-sha-256-jj
git push origin --delete AC-972-rebased
git push origin --delete AC-983
git push origin --delete AC-992_nest-key-pages-with-key-books
git push origin --delete DO-23-generator-docs
git push origin --delete DO-30
git push origin --delete DO-57-ci-fuzz
git push origin --delete DO-59-debug-decode
git push origin --delete DO-73-remove-node
git push origin --delete DO-76-deactivate-validator
git push origin --delete DO-92-activation
git push origin --delete Rosatte-construction-funs
git push origin --delete ac-126-test-1-q-ben-nodes
git push origin --delete acc-db
git push origin --delete activation
git push origin --delete add-chain-validation-engine
git push origin --delete add-validator-opcodes
git push origin --delete another-attempt-at-terraform
git push origin --delete api-debug
git push origin --delete api-gold-file
git push origin --delete api-v3-spec
git push origin --delete bpt2
git push origin --delete bpt3
git push origin --delete bridge-refunds
git push origin --delete bug-fix-synth-receipts
git push origin --delete bugfix/AC-364-merged-with-AC-200
git push origin --delete bugfix/AC-554-fix-chain-id-from-cli
git push origin --delete cherry-pick-550b00c0
git push origin --delete ci-health
git push origin --delete cli-default-url'
git push origin --delete dashboards
git push origin --delete data-hash
git push origin --delete database
git push origin --delete database-benchmark-index
git push origin --delete database-interface
git push origin --delete database-no-mutex
git push origin --delete dbrepair-read-bug
git push origin --delete debug-factom-genesis
git push origin --delete debug-flaky
git push origin --delete debug-sign-address
git push origin --delete deploy-aws-ecr
git push origin --delete disable-space-check
git push origin --delete eip712-mask
git push origin --delete enable-result-pipelines
git push origin --delete enable-some-tests
git push origin --delete enable-tests-in-ci
git push origin --delete ethan-tx-payload
git push origin --delete ethan-work
git push origin --delete expand-jsonrpc-api
git push origin --delete explorer-proxy
git push origin --delete factom-import
git push origin --delete factom-import-nonce
git push origin --delete factom-import-ps
git push origin --delete failure-chain-poc
git push origin --delete faucet-break-consensus
git push origin --delete fct2acme
git push origin --delete files
git push origin --delete fix-stall-script
git push origin --delete fix-state-db-test
git push origin --delete fix-to-allow-faucet-to-resolve-nonce
git push origin --delete foo
git push origin --delete for-staking-api-v3
git push origin --delete generatel-schema
git push origin --delete get-original-value
git push origin --delete get-record-from-parent
git push origin --delete go-mod-tidy
git push origin --delete golangci-repro-4482
git push origin --delete gold
git push origin --delete hashed-time-locks
git push origin --delete immutable-values
git push origin --delete java-sdk
git push origin --delete light
git push origin --delete load-test
git push origin --delete load-test-tweak
git push origin --delete memoize-record-keys
git push origin --delete memoize-url-join-path
git push origin --delete merkle-hash
git push origin --delete mexc
git push origin --delete move-chain-queries
git push origin --delete multi-network-node
git push origin --delete new-config
git push origin --delete on-board
git push origin --delete partial-merkle-tree
git push origin --delete performance-tweaks
git push origin --delete pgp
git push origin --delete playbooks-notebooks
git push origin --delete poc-advanced-auth
git push origin --delete pre-3156
git push origin --delete pre-AC-3329
git push origin --delete provide-helpers-for-internal-api
git push origin --delete proxy-data-entries
git push origin --delete query-direct
git push origin --delete rc2
git push origin --delete rc3
git push origin --delete refactor-signatures
git push origin --delete remove-cli
git push origin --delete reset-consensus-script
git push origin --delete revert-18df342b
git push origin --delete revert-c827f710
git push origin --delete run-ci-on-gitlab
git push origin --delete sdk
git push origin --delete separate-daemon
git push origin --delete serve-db
git push origin --delete set-dependency-scanning-config-1
git push origin --delete set-sast-config-1
git push origin --delete show-vars
git push origin --delete sign-image
git push origin --delete simulator-tracing
git push origin --delete sphereon/kotlin-mp-sdk
git push origin --delete stevenmasley/readme_edits
git push origin --delete stub-create-token
git push origin --delete terraform-saving-work
git push origin --delete terraform-test
git push origin --delete test-2
git push origin --delete test-AC-489
git push origin --delete test-target
git push origin --delete testnet-revert
git push origin --delete tests-and-stuff
git push origin --delete work-on-api
git push origin --delete work-on-executor-consistency
git push origin --delete work-on-restore-snapshot
git push origin --delete work-on-state-buckets
git push origin --delete write-batch
git push origin --delete x-errors
git push origin --delete x-move-pkg
