stages:
- pre test
- test
- post test
- pre deploy
- deploy
- post deploy

variables:
  BOLD_RED: '\e[1;31m'
  NO_COLOR: '\e[0m'
  SECTION: '\e[0K'

.go:
  # https://github.com/golang/go/issues/53762
  # https://github.com/golang/go/issues/53254
  image: golang:1.18.3
  cache:
    key: go-mod-cache
    paths:
      - .go-mod-cache
  variables:
    GOMODCACHE: ${CI_PROJECT_DIR}/.go-mod-cache

.rules all:
  rules:
  - if: $CI_PIPELINE_SOURCE != ''