.rules devnet: &rules
  - if: $CI_COMMIT_BRANCH == 'develop' && $CI_PIPELINE_SOURCE != 'merge_request_event'

configure devnet:
  stage: pre deploy
  extends: .go
  needs: [ git describe ]
  rules: *rules
  script:
  - |
    function init {
      mv config/$2 config-$1
      (cd config-$1 && tar czf ../config-$1.tar.gz *)
    }
  - build-daemon
  - build-daemon linux arm64
  - ./accumulated init network --no-website -w config scripts/management/data/testnet-canary.json
  - init DevNet.Directory dn
  - init DevNet.Zion bvn0
  - init DevNet.Yellowstone bvn1
  artifacts:
    paths:
    - config-*.tar.gz
    - accumulated-*

.devnet deploy:
  stage: deploy
  needs: [ configure devnet, go test ]
  rules: *rules
  tags:
  - linux
  - docker
  - accumulate
  image: ubuntu
  script:
  - apt-get -y update && apt-get -y install ssh
  - mkdir ~/.ssh
  - cp ${SSH_KNOWN_HOSTS} ~/.ssh/known_hosts
  - cp ${SSH_PRIV_KEY} ~/.ssh/id_rsa
  - cp ${SSH_PUB_KEY} ~/.ssh/id_rsa.pub
  - chmod -R 600 ~/.ssh
  - ./scripts/ci/devnet-deploy.sh

devnet deploy 1/4:
  extends: .devnet deploy
  variables:   { HOST: 172.31.4.106,  NETWORK: Zion,         NODE: 0, DN_NODE: 0, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://172.31.4.106:8080',  name: Zion/0 }

devnet deploy 2/4:
  extends: .devnet deploy
  variables:   { HOST: 172.31.11.185, NETWORK: Zion,         NODE: 1, DN_NODE: 1, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://172.31.11.185:8080', name: Zion/1 }

devnet deploy 3/4:
  extends: .devnet deploy
  variables:   { HOST: 172.31.11.104, NETWORK: Yellowstone,  NODE: 0, DN_NODE: 2, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://172.31.11.104:8080', name: Yellowstone/0 }

devnet deploy 4/4:
  extends: .devnet deploy
  variables:   { HOST: 172.31.13.8,   NETWORK: Yellowstone,  NODE: 1, DN_NODE: 3, BIN: accumulated-linux-arm64 }
  environment: { url: 'http://172.31.13.8:8080',   name: Yellowstone/1 }

.devnet validate:
  stage: post deploy
  extends: .go
  needs: [ devnet deploy 1/4, devnet deploy 2/4, devnet deploy 3/4, devnet deploy 4/4 ]
  rules: *rules
  variables:
    ACC_API: https://devnet.accumulatenetwork.io/v2
    # set mnemonic for predictable addresses
    MNEMONIC: yellow yellow yellow yellow yellow yellow yellow yellow yellow yellow yellow yellow

devnet validate:
  extends: .devnet validate
  allow_failure: true
  script:
  - apt-get -y update && apt-get -y install jq xxd
  - ./scripts/ci/validate.sh

.devnet matrix 1/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_1.1.sh

.devnet matrix 2/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_2.1.sh
   - ./scripts/matrix/test_case_2.2.sh
   - ./scripts/matrix/test_case_2.3.sh
   - ./scripts/matrix/test_case_2.4.sh
   - ./scripts/matrix/test_case_2.5.sh
   - ./scripts/matrix/test_case_2.6.sh
   - ./scripts/matrix/test_case_2.7.sh

.devnet matrix 3/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_3.1.sh
   - ./scripts/matrix/test_case_3.2.sh
   - ./scripts/matrix/test_case_3.3.sh
   - ./scripts/matrix/test_case_3.4.sh

.devnet matrix 4/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_4.1.sh
   - ./scripts/matrix/test_case_4.2.sh
   - ./scripts/matrix/test_case_4.3.sh
   - ./scripts/matrix/test_case_4.4.sh
   - ./scripts/matrix/test_case_4.5.sh
   - ./scripts/matrix/test_case_4.6.sh
   - ./scripts/matrix/test_case_4.7.sh
   - ./scripts/matrix/test_case_4.8.sh

.devnet matrix 5/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_5.1.sh
   - ./scripts/matrix/test_case_5.2.sh

.devnet matrix 6/6:
   extends: .devnet validate
   script:
   - ./scripts/matrix/test_case_6.1.sh
   - ./scripts/matrix/test_case_6.2.sh
   - ./scripts/matrix/test_case_6.3.sh
   - ./scripts/matrix/test_case_6.4.sh
   - ./scripts/matrix/test_case_6.5.sh
   - ./scripts/matrix/test_case_6.6.sh
   - ./scripts/matrix/test_case_6.7.sh
