NodeType:
  Validator:
    value: 1
  Follower:
    value: 2

PortOffset:
  TendermintP2P:
    value: 0
  TendermintRpc:
    value: 1
  AccumulateP2P:
    value: 2
  Prometheus:
    value: 3
  AccumulateApi:
    value: 4
