name: Merge

on:
  pull_request:
    # Rerun when the PR is edited, such as changing the target
    types: [ opened, synchronize, edited, reopened ]

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Only merge into `develop`
        # Fail unless the base branch is 'develop'
        run: |
          if [ "$GITHUB_BASE_REF" != "develop" ]; then
            echo -e "\033[1;31mMerging into $GITHUB_BASE_REF is not allowed.\033[0m"
            false
          fi